[package]
name = "crowe"
version = "0.1.0"
authors = ["timdelisle <tg339@cornell.edu>"]

[dependencies]
rustc-serialize = "0.3"
syncbox = "0.2.4"
eventual = "0.1.5"
threadpool= "0.2.1"
num_cpus = "0.2"